# Generated by Django 4.2.7 on 2024-04-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alinaverenaapi', '0002_purchase_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
