# Generated by Django 4.2.7 on 2024-05-01 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alinaverenaapi", "0003_alter_purchase_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clients favorite articles.",
            ),
        ),
    ]
